---
- name: update previous release to newest release
  hosts: all
  tasks:
    - name: get latest release version
      ansible.builtin.uri:
        url: https://api.github.com/repos/paperless-ngx/paperless-ngx/releases/latest
        method: GET
      register: latest_release
    - name: parse latest release version
      ansible.builtin.set_fact:
        paperlessng_version: "{{ latest_release.json['tag_name'] }}"
        
    - name: update to newest paperless-ngx release
      ansible.builtin.include_role:
        name: ansible-paperless-ngx
