---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_focal
    image: jrei/systemd-ubuntu:20.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    published_ports:
      - 8000:8000
    # exposed_ports:
    #   - 8000/tcp
    override_command: false
  - name: ubuntu_jammy
    image: jrei/systemd-ubuntu:22.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    published_ports:
      - 8001:8000
    override_command: false
# debian 9 stretch only has Python 3.5 which is EOL and breaks multiple dependencies
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - create
    - prepare
    - verify
    - syntax
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy