---
- name: install previous release
  hosts: all
  tasks:
    - name: set previous version as installation target
      ansible.builtin.set_fact:
        paperlessng_version: v1.8.0

    - name: install previous paperless-ngx release
      ansible.builtin.include_role:
        name: ansible
