---
- name: Install previous release
  hosts: all
  tasks:
    - name: Set previous version as installation target
      ansible.builtin.set_fact:
        paperlessng_version: v1.7.1

    - name: Install previous paperless-ngx release
      ansible.builtin.include_role:
        name: ansible
