---
- name: Verify
  hosts: all
  gather_facts: false

  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Check if webserver is up
      ansible.builtin.uri:
        url: http://{{ paperlessng_listen_address }}:{{ paperlessng_listen_port }}
        status_code: [200, 302]
        return_content: true
      register: landingpage
      failed_when: "'Sign in</button>' not in landingpage.content"

    - name: Generate random name and content
      ansible.builtin.set_fact:
        content: "{{ lookup('password', '/dev/null length=65536 chars=ascii_letters') }}"
        filename: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"

    - name: Check if document posting works
      ansible.builtin.uri:
        url: http://{{ paperlessng_listen_address }}:{{ paperlessng_listen_port }}/api/documents/post_document/
        method: POST
        body_format: form-multipart
        body:
          document:
            content: "{{ content }}"
            filename: "{{ filename }}.txt"
        headers:
          Authorization: Basic {{ (paperlessng_superuser_name + ":" + paperlessng_superuser_password) | b64encode }}
          Content-Type: text/plain
        return_content: true
      register: post_document
      failed_when: "'OK' not in post_document.content"

    # - name: Output post register
    #   ansible.builtin.debug:
    #     var: post_document
    #   run_once: true

    - name: Verify uploaded document has been accepted
      ansible.builtin.uri:
        url: http://{{ paperlessng_listen_address }}:{{ paperlessng_listen_port }}/api/logs/paperless/
        headers:
          Authorization: Basic {{ (paperlessng_superuser_name + ":" + paperlessng_superuser_password) | b64encode }}
        return_content: true
      register: logs
      failed_when: ('Consuming ' + filename + '.txt') not in logs.content

    # - name: Output logs register
    #   ansible.builtin.debug:
    #     var: logs
    #   run_once: true

    - name: Sleep till consumption finished
      ansible.builtin.pause:
        seconds: 10

    - name: Verify uploaded document has been consumed
      ansible.builtin.uri:
        url: http://{{ paperlessng_listen_address }}:{{ paperlessng_listen_port }}/api/logs/paperless/
        headers:
          Authorization: Basic {{ (paperlessng_superuser_name + ":" + paperlessng_superuser_password) | b64encode }}
        return_content: true
      register: logs
      failed_when: filename + ' consumption finished' not in logs.content

    - name: Get documents
      ansible.builtin.uri:
        url: http://{{ paperlessng_listen_address }}:{{ paperlessng_listen_port }}/api/documents/
        headers:
          Authorization: Basic {{ (paperlessng_superuser_name + ":" + paperlessng_superuser_password) | b64encode }}
        return_content: true
      register: documents

    - name: Set document index
      ansible.builtin.set_fact:
        index: "{{ documents.json['results'][0]['id'] }}"

    - name: Verify uploaded document is avaiable
      ansible.builtin.uri:
        url: http://{{ paperlessng_listen_address }}:{{ paperlessng_listen_port }}/api/documents/{{ index }}/
        headers:
          Authorization: Basic {{ (paperlessng_superuser_name + ":" + paperlessng_superuser_password) | b64encode }}
        return_content: true
      register: document
      failed_when: "'Not found.' in document.content or content not in document.json['content']"

    - name: Check if deleting uploaded document works
      ansible.builtin.uri:
        url: http://{{ paperlessng_listen_address }}:{{ paperlessng_listen_port }}/api/documents/bulk_edit/
        method: POST
        body_format: json
        body:
          documents: ["{{ index }}"]
          method: delete
          parameters: {}
        headers:
          Authorization: Basic {{ (paperlessng_superuser_name + ":" + paperlessng_superuser_password) | b64encode }}
      register: delete_document
      failed_when: "'OK' not in delete_document.json['result']"
